# Generated by Django 4.0.6 on 2023-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
